### ISSUE TITLE
Cannot import library when using Jest

### ISSUE THREAD

**Issue by lnhrdt** [carhartl/typescript-cookie#110]
**Describe the bug**

The library works great when running my application, but fails to import when running tests with Jest. Tests fails with the error message:

````
Cannot find module 'typescript-cookie' from 'path/to/my/file.tsx'
````

I found others with the same problem on [this Stack Overflow post](https://stackoverflow.com/q/72706823) leading me to believe it's an issue with `typescript-cookie`.

**Additional context**

I'm using the library within a project created with create-react-app. In the above linked Stack Overflow post, the other user had the same error within a project created with "VITE + TS."

**Comment by carhartl** [comment]
Could you please share your jest config file?

**Comment by carhartl** [comment]
Also I will need the exact error message.

**Comment by lnhrdt** [comment]
@carhartl thanks for taking a look at this. I put together [a repo for you that reproduces the issue as simply as possible](https://github.com/lnhrdt/typescript-cookie-issue-110).

I created a new Create React App project with Typescript by running:

```
yarn create react-app my-app --template typescript
```

Then I simply added `typescript-cookie` as a dependency and imported it in the application ([here's the commit](https://github.com/lnhrdt/typescript-cookie-issue-110/commit/5139576433986cf098ff1caba245f62077f4a8cb)). Just doing that much causes the default test included with a new Create React App project (`src/App.test.tsx`) to fail with this error:

```
  ● Test suite failed to run

    Cannot find module 'typescript-cookie' from 'src/App.tsx'

    Require stack:
      src/App.tsx
      src/App.test.tsx

      2 | import logo from './logo.svg';
      3 | import './App.css';
    > 4 | import {getCookie} from 'typescript-cookie';
        | ^
      5 |
      6 | function App() {
      7 |   return (

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/App.tsx:4:1)
```

Let me know if I can help you diagnose the issue any further.

**Comment by carhartl** [comment]
I've pushed https://github.com/carhartl/typescript-cookie/releases/tag/v1.0.4

**Comment by niltonxp2** [comment]
![image](https://user-images.githubusercontent.com/88057912/187267713-7511f596-f85a-43de-b41f-a599495954bd.png)

I'm still getting this error on the version 1.0.4

**Comment by ariardian** [comment]
> ![image](https://user-images.githubusercontent.com/88057912/187267713-7511f596-f85a-43de-b41f-a599495954bd.png)
> 
> I'm still getting this error on the version 1.0.4

same here

**Comment by O-Mutt** [comment]
![image](https://user-images.githubusercontent.com/872224/195374897-7586a36f-cb9c-42bc-9fa9-efc2984a3b71.png)
+1
```module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  testEnvironmentOptions: {
    customExportConditions: ['node', 'node-addons'],
  },
  moduleFileExtensions: [
    'js',
    'ts',
    'json',
    'vue',
    'tsx',
    'jsx',
    'mjs',
    'cjs',
    'd.ts',
  ],
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
    '^.+\\.vue$': '@vue/vue3-jest',
  },
  setupFilesAfterEnv: ['<rootDir>/src/jest.setup.ts'],
  modulePaths: ['<rootDir>'],
  moduleDirectories: ['node_modules', 'src'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  globals: {
    'ts-jest': {
      diagnostics: {
        ignoreCodes: [1343],
      },
      astTransformers: {
        before: [
          {
            path: 'node_modules/ts-jest-mock-import-meta',
            options: {
              metaObjectReplacement: {
                // This is important, we are mocking the `import.meta.env` here
                env: {
                  MODE: 'dev',
                },
              },
            },
          },
        ],
      },
    },
  },
};
```

**Comment by carhartl** [comment]
Looks like this still occurs as soon as another 3rd-party package is importing typescript-cookie?

**Comment by carhartl** [comment]
@justindmyers Could you post your package.json and jest config?

**Comment by cenobitedk** [comment]
Package exports ECMAScript Modules but Jest doesn't like it. https://jestjs.io/docs/ecmascript-modules

In my case I used `moduleNameMapper` and added this
```js
    'typescript-cookie': 'js-cookie',
```

That should help you get going.

Below is the full error from Jest, and they even provide different help options.

```
    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /node_modules/typescript-cookie/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './dist/typescript-cookie.mjs'

```

**Comment by carhartl** [comment]
This might also help: https://www.npmjs.com/package/jest-esm-transformer

**Comment by liamtarpey** [comment]
I'm also seeing the same issue:

Version: `"typescript-cookie": "^1.0.6"`

jest.config.js:

```
module.exports = {
    collectCoverage: true,
    verbose: true,
    collectCoverageFrom: [
        '**/*.{js,jsx,ts,tsx}',
        '!**/node_modules/**',
        '!**/__tests__/**',
        '!**/*.stories.{js,jsx,ts,tsx}',
    ],
    coverageReporters: ['text-summary', 'html', 'lcov'],
    coverageThreshold: {
        global: {
            branches: 80,
            functions: 80,
            lines: 80,
            statements: -10,
        },
    },
    rootDir: 'src',
    coverageDirectory: '../coverage',
    collectCoverageFrom: ['**/ecommerce-origin/**/*.ts', '**/common/**/*.ts', '!index.ts'],
    preset: 'ts-jest',
};

```

package.json:
```
{
    "name": "my-test-app",
    "repository": "git://github.com/liamtarpey/my-test-app.git",
    "description": "Test",
    "version": "0.0.1",
    "main": "./dist/index.js",
    "module": "./dist/index.esm.js",
    "source": "./src/index.ts",
    "types": "./dist/index.d.ts",
    "scripts": {
        "prepack": "yarn build",
        "build": "rollup -c",
        "test": "yarn test:lint && yarn test:jest --passWithNoTests",
        "test:jest": "yarn jest",
        "test:lint": "eslint --max-warnings 0 --ext .js,.jsx,.ts,.tsx ./ && tsc --noEmit"
    },
    "publishConfig": {
        "access": "restricted",
        "registry": "https://npm.pkg.github.com"
    },
    "license": "UNLICENSED",
    "devDependencies": {
        "@rollup/plugin-typescript": "^8.2.0",
        "@types/jest": "^29.5.1",
        "babel-jest": "^29.5.0",
        "eslint": "^7.21.0",
        "jest": "^29.5.0",
        "prettier": "^2.2.1",
        "rollup": "^2.40.0",
        "ts-jest": "^29.1.0",
        "tslib": "^2.1.0",
        "typescript": "^4.9.5"
    },
    "dependencies": {
        "typescript-cookie": "^1.0.6"
    }
}
```

![Screenshot 2023-04-27 at 16 51 18](https://user-images.githubusercontent.com/4904859/234917208-6586ab3f-edf2-490d-abf3-e343a1f12dbf.png)

@carhartl - does this help debug at all?

Thanks!

**Comment by armin-m-garcia** [comment]
Issue still remains.  I wound up replacing the typescript-cookie library.

**Comment by carhartl** [comment]
@armin-m-garcia Fair enough.. I can‘t reproduce the issue out of thin air though. My guess though is that you‘re relying on CommonJS modules (which jest does by default), which this library isn’t supporting, and then you need to set up a transformer for jest.

**Comment by carhartl** [comment]
@armin-m-garcia PS: Of all the information you could have given in order to help debug the issue for me, your’s is the most useless one.
